Part 1: Vladislav Pochernin
polis-vk/2022-ads pull request #1
Opened 2022-09-21 09:25 UTC by vspochernin

2022-09-21 17:33 UTC, lamtev requested changes

2022-09-21 17:33 UTC, lamtev commented on src/main/java/Part1Task2.java
> +        LinkedList<Integer> list = new LinkedList<>();
Из [описания](https://github.com/polis-vk/2022-ads#%D0%B4%D0%B7-1-%D0%B4%D0%B5%D0%B4%D0%BB%D0%B0%D0%B9%D0%BD-27092022-182959) домашки
> В задачах, где требуется реализовать структуру данных (стек, дек или очередь), использовать готовые реализации из Java нельзя

`LinkedList` является готовой реализацией `Queue`, что нарушает условия. Придется в этой, следующей и последней задаче поправить

2022-09-21 18:48 UTC, vspochernin commented on src/main/java/Part1Task2.java
> +        LinkedList<Integer> list = new LinkedList<>();
Действительно, упустил этот момент.
Реализовал собственный двусвязный список для задач 2, 3 и 6: fb8cc9236cb4b089e20c41f2926496621c089dd9

2022-09-24 16:50 UTC, lamtev approved these changes
Зачтено

2022-09-24 16:50 UTC, lamtev commented on src/main/java/SolveTemplate.java
> +import java.io.BufferedReader;
данный файл не нужен

2022-09-24 16:50 UTC, lamtev commented on src/main/java/Part1Task6.java
> +        private Node tail = null;
не нужно присваивать дефолтные значения

2022-09-24 16:50 UTC, lamtev commented on src/main/java/Part1Task6.java
> +            int result = head.data;
на пустом списке случится npe, что не является лучшим решением

2022-09-24 16:50 UTC, lamtev commented on src/main/java/Part1Task4.java
> +                    System.exit(-1);
System exit завершит весь процесс, что практически всегда в реальных приложениях не является тем, что нам надо

2022-09-24 16:50 UTC, lamtev commented on src/main/java/Part1Task5.java
> +        int a, b;
объявление нескольких переменных на одной строке не является хорошей практикой

2022-09-24 16:50 UTC, closed without merging