part4 - Emelyanov Vitaliy
polis-vk/2022-ads pull request #112
Opened 2022-10-16 20:38 UTC by GenryEden

2022-10-23 11:54 UTC, ysp2000 requested changes
В целом, ок. Решено 4 из 5 задач. Если есть возможность, скобки лучше доделать.

По баллам, пока 7 / 10, с поправленными скобками будет 9. В ведомость проставлю после контрольной во вторник.

2022-10-23 11:54 UTC, ysp2000 commented on src/main/java/company/vk/polis/ads/part4/GenryEden/EOlymp1087.java
> +            return writeToHashAndReturn(inp,
Возможно не акцентировал это на лекции, но не всегда оптимально делать этот переход. Например, для корректной последовательности`"()()` оптимальным будет разбиение на `()`, `()`, а не `(`, `)(`, `)`.

2022-10-24 09:56 UTC, GenryEden commented on src/main/java/company/vk/polis/ads/part4/GenryEden/EOlymp1087.java
> +            return writeToHashAndReturn(inp,
старый файл оставлен в неизменном виде, добавлен файл EOlymp1087Rework

2022-11-01 17:08 UTC, ysp2000 commented
Ага, скобки принимаю. Выставил 9 баллов в ведомость. ПР закрываю

2022-11-01 17:08 UTC, closed without merging