part 3
polis-vk/2022-ads pull request #121
Opened 2022-10-17 15:23 UTC by Lotsn

https://www.eolymp.com/ru/submissions/11779333 - хипуй
https://www.eolymp.com/ru/submissions/11779592 - найти медиану
https://www.eolymp.com/ru/submissions/11792035 - простая сортировка
Spiridonov D.K.

2022-10-20 14:50 UTC, lamtev requested changes
Прошу ответить на вопросы

2022-10-20 14:50 UTC, lamtev commented on src/main/java/company/vk/polis/ads/TopK.java
> +        MinHeap<T> heap = new MinHeap<>(100);
Почему 100?

2022-10-20 14:50 UTC, lamtev commented on src/main/java/company/vk/polis/ads/MinHeap.java
> +            this.arr = (T[]) new Comparable[size * 2];
почему size * 2?

2022-10-20 16:05 UTC, Lotsn commented on src/main/java/company/vk/polis/ads/MinHeap.java
> +            this.arr = (T[]) new Comparable[size * 2];
То же самое что и выше.

2022-10-20 16:07 UTC, lamtev commented on src/main/java/company/vk/polis/ads/MinHeap.java
> +            this.arr = (T[]) new Comparable[size * 2];
А выше это как?

2022-10-20 16:25 UTC, lamtev commented on src/main/java/company/vk/polis/ads/TopK.java
> +        MinHeap<T> heap = new MinHeap<>(100);
Теперь понял, кажется

Обычно, когда размер структуры данных заранее известен, его и задают

И в этом случае, довольно странно будет, что внутри создастся массив в 2 раза большего размера. То есть, раз есть возможность задать размер, то значит, что это скорее всего тот размер, которого будет достаточно, и в 2 раза больше памяти выделять вовсе не надо

2022-10-20 16:29 UTC, Lotsn commented on src/main/java/company/vk/polis/ads/TopK.java
> +        MinHeap<T> heap = new MinHeap<>(100);
Да, согласен, это у меня диссонанс небольшой произошёл, умножение на двойку в конструкторе нужно убрать.
Я изначально хотел сделать увеличение в два раза при переполнении массива, зачем-то сделал здесь умножение. Потом сделал там где надо, а отсюда убрать забыл)

2022-10-20 19:50 UTC, Lotsn commented on src/main/java/company/vk/polis/ads/TopK.java
> +        MinHeap<T> heap = new MinHeap<>(100);
Мне нужно исправить недочеты?

2022-10-21 19:25 UTC, lamtev requested changes

2022-10-21 19:25 UTC, lamtev commented on src/main/java/company/vk/polis/ads/TopK.java
> +                heap.insert(list.get(i));
сколько в итоге будет элементов в куче?

сколько в массиве, который возвращает функция?

какая общая сложность по времени у такого алгоритма?

2022-12-18 07:59 UTC, lamtev commented
Остались вопросы без ответа..
Ну и ладно. 5/10, т.к. все задания присланы после дедлайна

2022-12-18 07:59 UTC, closed without merging