Part 1 Popov Ivan
polis-vk/2022-ads pull request #2
Opened 2022-09-21 16:40 UTC by PopovIV

2022-09-21 17:36 UTC, lamtev requested changes

2022-09-21 17:36 UTC, lamtev commented on src/main/java/TaskB.java
> +        LinkedList<Integer> queue = new LinkedList<>();
Из [описания](https://github.com/polis-vk/2022-ads#%D0%B4%D0%B7-1-%D0%B4%D0%B5%D0%B4%D0%BB%D0%B0%D0%B9%D0%BD-27092022-182959) домашки
> В задачах, где требуется реализовать структуру данных (стек, дек или очередь), использовать готовые реализации из Java нельзя

`LinkedList` является готовой реализацией `Queue`, что нарушает условия. Придется в этой, следующей и последней задаче поправить

2022-09-23 17:35 UTC, PopovIV commented on src/main/java/TaskB.java
> +        LinkedList<Integer> queue = new LinkedList<>();
Справедливо, я как-то неправильно интерпретировал это задание.
Сейчас все переделал на собственные реализации структур данных.

2022-09-24 17:00 UTC, lamtev approved these changes
Зачтено

2022-09-24 17:00 UTC, closed without merging