Part2: Emelyanov Pavel
polis-vk/2022-ads pull request #36
Opened 2022-09-29 08:47 UTC by llav3ji2019

2022-10-01 21:24 UTC, lamtev requested changes
Прошу оценить время работы решения задачи E. И, если оно не O(n), то исправить на O(n), как просят в задании

2022-10-01 21:24 UTC, lamtev commented on src/main/java/HW2TaskE.java
> +                result.insert(midIndex, getLetterFromIndex(i));
insert работает за O(n). Предлагаю оценить время работы всего алгоритма задачи. Думаю, что получается уложиться во временные лимиты в тестирующей системе, потому что внутри insert используется быстрое копирование через arraycopy. Но тем не менее, очень похоже, что сложность алгоритма получилась больше, чем O(n). А по заданию нужно O(n)

2022-10-01 22:03 UTC, llav3ji2019 commented on src/main/java/HW2TaskE.java
> +                result.insert(midIndex, getLetterFromIndex(i));
Исправлено

2022-10-02 06:08 UTC, lamtev approved these changes
зачтено

2022-10-02 06:08 UTC, closed without merging