Part2, Nikita BANDURIN
polis-vk/2022-ads pull request #38
Opened 2022-09-29 15:17 UTC by NIKITry

A and B are done

2022-10-02 06:30 UTC, lamtev commented
Будем претендовать только на баллы от 2 задач? Это 4 балла максимум. Или подождать еще решения других задач?

2022-10-02 06:32 UTC, lamtev requested changes
Претендуете только на баллы от 2 задач? Это 4 балла максимум

2022-10-02 10:22 UTC, NIKITry commented
> Претендуете только на баллы от 2 задач? Это 4 балла максимум. Или подождать решения остальных задач?

Да, ждём. Я просто решил, что сделал, скинуть

2022-10-05 14:06 UTC, NIKITry commented on src/main/java/company/vk/polis/ads/ResultsOlympiads.java
> +        });
Я проверял компаратор на правильность, а потом, написав сортировку, забыл убрать наивную сортировку и с ней прогнал тесты. Сейчас отправил коммит, я вообще переписал merge, ибо старый не работал, как выяснилось, должным образом.

2022-10-05 14:09 UTC, NIKITry commented on src/main/java/company/vk/polis/ads/Dispersion.java
> +                if (array[j] == i) {
столько, сколько элементов из диапазона k есть в массиве

2022-10-05 14:29 UTC, lamtev commented on src/main/java/company/vk/polis/ads/Dispersion.java
> +                if (array[j] == i) {
можно в "О-большое" нотации?

2022-10-05 14:35 UTC, lamtev commented on src/main/java/company/vk/polis/ads/ResultsOlympiads.java
> +    public static <T> void mergeSort(ArrayList<T> array, int fromInclusive, int toExclusive, Comparator<T> comparator) {
До этого была интересная нерекурсивная реализация, которую вполне можно было добить до рабочего состояния. Жаль, что было принято решение полностью поменять реализацию

2022-10-05 14:39 UTC, NIKITry commented on src/main/java/company/vk/polis/ads/Dispersion.java
> +                if (array[j] == i) {
O(n*k)

2022-10-05 14:40 UTC, lamtev commented on src/main/java/company/vk/polis/ads/ResultsOlympiads.java
> +    public static <T> void mergeSort(ArrayList<T> array, int fromInclusive, int toExclusive, Comparator<T> comparator) {
лучше сначала сделать следующую домашку, там посложнее задачки имхо

2022-10-05 14:40 UTC, NIKITry commented on src/main/java/company/vk/polis/ads/Dispersion.java
> +                if (array[j] == i) {
Если k сильно меньше n, то можно и O(n) думаю оставить

2022-10-05 15:17 UTC, lamtev commented on src/main/java/company/vk/polis/ads/Dispersion.java
> +                if (array[j] == i) {
вот. O(n*k). То есть в целом алгоритм получился не таким эффективным, как можно было бы - за O(n + k). не буду требовать улучшения, но хочется, чтобы было понимание, что улучшить можно. у нас k = 108, n = 100_000

итого будем иметь в конкретном месте 10.8 M сравнений. а могло бы быть 100 K

2022-10-06 08:54 UTC, lamtev approved these changes
зачтено. т.к. до дедлайна сортировка слиянием была не рабочей, за эту задачу 1 балл из 2. итого 7 баллов

2022-10-06 08:54 UTC, closed without merging