Part2 Gabrielyan Arthur
polis-vk/2022-ads pull request #40
Opened 2022-09-30 22:04 UTC by Gilfoyal

solved

2022-10-05 09:23 UTC, lamtev requested changes
Просьба ответить на вопросы

2022-10-05 09:23 UTC, lamtev commented on src/main/java/company/vk/polis/ads/TaskE.java
> +        int[] letters = new int[26];
Почему 26? Как получилось это число?

2022-10-05 09:23 UTC, lamtev commented on src/main/java/company/vk/polis/ads/TaskE.java
> +            letters[c - 'A'] += 1;
Как мы так выполняем вычитание с символами?

2022-10-05 09:23 UTC, lamtev commented on src/main/java/company/vk/polis/ads/TaskE.java
> +        }
Какое время работы у этого участка кода относительно n и k?

2022-10-06 13:43 UTC, Gilfoyal commented on src/main/java/company/vk/polis/ads/TaskE.java
> +            letters[c - 'A'] += 1;
Ответил Вам в личном сообщении в ТамТам

2022-10-06 14:12 UTC, Gilfoyal commented on src/main/java/company/vk/polis/ads/TaskE.java
> +        int[] letters = new int[26];
У нас 26 букв в латинском алфавите, в данный момент мы находим какое количество раз встречается каждая из букв, путем инкремента элемента массива который стоит на неком месте, условно наш массив это алфавит с индексами, данный прием я взял из counting sort, она была в этом же списке задач

2022-10-06 16:24 UTC, lamtev commented on src/main/java/company/vk/polis/ads/TaskC.java
> +        Member[] RightArray = new Member[n2];
При таком подходе происходит больше аллокаций массивов, чем могло бы быть. Можно перед сортировкой создать всего 1 вспомогательный массив длины n и пользоваться им на каждом уровне рекурсии

исправлять не требую, но понимать это полезно

2022-10-09 16:34 UTC, lamtev approved these changes
зачтено

2022-10-09 16:34 UTC, closed without merging