Part1
polis-vk/2022-ads pull request #45
Opened 2022-10-01 15:55 UTC by IgnatYuklyaevskiy

У меня все задачи полностью прошли все тесты кроме четвёртой (там не пройдено 2 теста из 64 из-за времени)

2022-10-02 16:36 UTC, lamtev requested changes
Нужно во всех своих реализациях сделать size не вычисляемым за O(n), а хранимым в поле для доступа за O(1). И нужно чтобы в зависимости от структуры данных в реализации остались только необходимые поля (firstNode и lastNode в Stack/Queue/Deque, а так же next и prev в Node)

Чтобы получить баллы за задачу D, нужно довести ее до рабочего состояния на всех тестах в информатиксе. Возможно, дело в remove(index)

2022-10-02 16:36 UTC, lamtev commented on src/main/java/Part1_2.java
> +            return count;
size нужно хранить, чтобы не вычислять за O(n)

и тогда достаточно будет односвязного списка

2022-10-02 16:36 UTC, lamtev commented on src/main/java/Part1_3.java
> +        Node lastNode;
В стеке достаточно хранить 1 ссылку. Либо first, либо last. И достаточно односвязного списка. То есть тут в зависимости от того, что хранить first или last будет достаточно в нодах next или prev

2022-10-02 16:36 UTC, lamtev commented on src/main/java/Part1_4.java
> +    private Part1_4() {
Предположу, что из-за parentheses.remove(i) не укладывается решение во временные ограничения. remove(index) в LinkedList работает за O(n)

2022-10-16 12:24 UTC, lamtev commented
будут доделки, или закрываем ПР?

2022-10-16 14:20 UTC, IgnatYuklyaevskiy commented
Я доделаю попозже
Пока не закрываем

2022-12-18 07:53 UTC, lamtev commented
Без задачи D можно было получить 8 баллов. И хотя есть неисправленные недочеты в остальных заданиях, оцениваю их без снижения баллов
Итого 4 балла, т.к. задания присланы после дедлайна

2022-12-18 07:53 UTC, closed without merging