all done
polis-vk/2022-ads pull request #48
Opened 2022-10-02 16:57 UTC by IgnatYuklyaevskiy

Все задачи проходят тесты, кроме последней (там не проходит последние пару тестов на время)

2022-10-06 10:05 UTC, lamtev requested changes

2022-10-16 12:25 UTC, lamtev commented
будут доделки, или закрываем ПР?

2022-10-16 14:18 UTC, IgnatYuklyaevskiy commented
Я попозже доделаю

2022-12-18 07:56 UTC, lamtev commented
Простил отмеченные недочеты, в задачах, которые прошли все тесты. 8/10

2022-12-18 07:56 UTC, closed without merging