Porublev_Egor_HW2
polis-vk/2022-ads pull request #56
Opened 2022-10-03 21:10 UTC by FullFool03

A B D done with all tests

2022-10-06 17:40 UTC, lamtev requested changes

2022-10-06 17:40 UTC, lamtev commented on src/main/java/company/vk/polis/ads/Task_A.java
> +        }
Это решение некорректное. Неужели оно прошло тесты? Выделенный кусок кода выведет ровно не более чем k элементов. В том время когда их n

2022-10-06 17:40 UTC, lamtev commented on src/main/java/company/vk/polis/ads/Task_D.java
> +        Set<Integer> firstSet = new HashSet<>();
Из описания дз:

> В задаче D необходимо написать быструю сортировку.

Нужно переделать

2022-10-16 12:25 UTC, lamtev commented
будут доделки, или закрываем ПР?

2022-10-24 17:15 UTC, FullFool03 commented
ДА доделаю обязательно не закрывайте пр.

2022-12-18 07:48 UTC, lamtev commented
2 балла за задачу B
И еще 2 суммарно за 2 остальные, хоть 1 решена некорректно, а другая использовала HashSet
4/10

2022-12-18 07:48 UTC, closed without merging