Part3
polis-vk/2022-ads pull request #76
Opened 2022-10-09 16:01 UTC by NIKITry

Eolymp's tasks are done, do not close request, am going to try other tasks until Tuesday. All links with submissions you can see in file swith classes, also I add the links to each commit.

2022-10-11 12:49 UTC, lamtev requested changes

2022-10-11 12:49 UTC, lamtev commented on src/test/java/company.vk.polis.ads/TopKTest.java
> +    private static final int SEQUENCE_SIZE = 10_000_000;
За такое положен бан) нужно откатить изменение

2022-10-11 13:07 UTC, NIKITry commented on src/test/java/company.vk.polis.ads/TopKTest.java
> +    private static final int SEQUENCE_SIZE = 10_000_000;
откатил

2022-10-16 12:30 UTC, lamtev commented
зачтено. 8 баллов

2022-10-16 12:30 UTC, closed without merging