HW3 Seletskaya
polis-vk/2022-ads pull request #86
Opened 2022-10-11 12:56 UTC by sealisaa

Сделаны задачи с e-olymp:
1. Хипуй: https://www.eolymp.com/ru/submissions/11743022
2. Найти медиану 2: https://www.eolymp.com/ru/submissions/11748552
3. Простая сортировка: https://www.eolymp.com/ru/submissions/11743067

2022-10-16 14:13 UTC, lamtev requested changes

2022-10-16 14:13 UTC, lamtev commented on src/main/java/company/vk/polis/ads/TopK.java
> +        Collections.sort(result);
Для чего сортировка?

2022-10-18 10:51 UTC, sealisaa commented on src/main/java/company/vk/polis/ads/TopK.java
> +        Collections.sort(result);
Да, там действительно можно обойтись без сортировки и reverse
Поправила

2022-10-20 15:00 UTC, lamtev requested changes

2022-10-20 15:00 UTC, lamtev commented on src/main/java/company/vk/polis/ads/TopK.java
> +            result.add(minHeap.array[i]);
Из javadoc: 

> @return list with k max elements ordered descending

А тут у нас на 1 позиции в массиве будет минимум

Такое решение не пройдет тесты

Не могу понять, почему пайплайн зеленый, хотя как минимум MergeIterator не решен

2022-10-20 15:16 UTC, lamtev commented on src/main/java/company/vk/polis/ads/TopK.java
> +    private static class MinHeap<T extends Comparable<T>> {
А, это же max-куча, а не min, на самом деле

2022-10-20 15:18 UTC, sealisaa commented on src/main/java/company/vk/polis/ads/TopK.java
> +    private static class MinHeap<T extends Comparable<T>> {
Да, там на самом деле max-куча и массив в итоге будет отсортирован по убыванию
Пока переделывала, забыла переименовать кучу, прошу прощения(

2022-10-20 15:44 UTC, lamtev requested changes
Реализация TopK на Max-куче является некорректной. Тест скорее всего выполнялся, но это был плохой тест) В тесте явный был изъян, что он сортировал входные данные. Это уже пофикшено

Пример входных данных, на которых не сработает:

[10, 9, 8, 8, 11]
k=4

построили макс кучу из первых k элементов:

```text
       10
    9     8
 8 
```

heap.max = 10 < 11, поэтому извлекаем 10 и добавляем 11. Итого 10 не попадет в результирующий массив, а должна


Потом, даже если бы на max куче было корректно, то потом нет гарантии, что в массиве будут строго в порядке убывания расположены элементы. Вот пример кучи, где это не так

```text
    10
  8    9
6  7 
```

[10, 8, 9, 6, 7]

2022-10-21 19:20 UTC, lamtev approved these changes
Зачтено. 8 баллов

2022-10-21 19:20 UTC, closed without merging